### ISSUE TITLE
Roadmap for v0.1

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#9]
Coc is working now, but still lots of work ahead to make it a better tool.
Let me know if you have some ideas for it.

* [ ] Works in vim.
* [ ] Powerline/Airline/Lightline integration
* [ ] Add support for https://github.com/Shougo/neosnippet.vim
* [ ] Integration of [vscode-cpptools](https://github.com/Microsoft/vscode-cpptools) for C & C++
* [ ] Support lSP feature: document highlight
* [ ] Support lSP feature: document link

**Comment by iamcco** [comment]
is it possible to support code block detection like ncm2 with [ncm2-markdown-subscope](https://github.com/ncm2/ncm2-markdown-subscope) ?

**Comment by chemzqm** [comment]
@iamcco There is a plan for something like that, but not high priority for now.

**Comment by kdurant** [comment]
Can use it on Win10？

**Comment by fannheyward** [comment]
Microsoft's python-language-server is just released: https://github.com/Microsoft/python-language-server

According to https://github.com/Microsoft/vscode-python/blob/master/src/client/activation/languageServer.ts#L159, the VSCode-python can download LS bin.

**Comment by sandangel** [comment]
could you please consider adding emmet support? so I could use Tab to expand html markup without conflict with coc auto-complete

```sh
	" Use <Tab> for confirm completion.
	" Coc only does snippet and additional edit on confirm.
	inoremap <expr> <Tab> pumvisible() ? "\<C-y>" : "\<Tab>"

```

**Comment by chemzqm** [comment]
@sandangel you just need to extend the remap, like:
``` vim
  let g:user_emmet_leader_key = '<C-e>'
  let g:user_emmet_expandabbr_key = '<C-x><C-e>'
  imap <silent><expr> <Tab> <SID>expand()

  function! s:expand()
    if pumvisible()
      return "\<C-y>"
    endif
    let col = col('.') - 1
    if !col || getline('.')[col - 1]  =~# '\s'
      return "\<Tab>"
    endif
    return "\<C-x>\<C-e>"
  endfunction
```
Notice `imap` is used here so that you can't let emmet use the mapping for `<C-y>`

**Comment by sandangel** [comment]
I mean is it posible to add emmet suggestion to the popup menu like vscode?


![example](https://user-images.githubusercontent.com/22189661/47599268-36819400-d9e5-11e8-8019-e67cac82c818.gif)

**Comment by chemzqm** [comment]
It's possible by create a custom source, but I don't think it's useful since you can always expand emmet with it's own expand key, and it could be buggy.

**Comment by adelarsq** [comment]
@chemzqm Any idea if [VS Code Debug Protocol](https://code.visualstudio.com/docs/extensionAPI/api-debugging) will be supported?

**Comment by chemzqm** [comment]
@adelarsq I've thinked about it, but one big problem is I don't know how to make it easy to use, ex: I can't create buttons in terminal vim.

**Comment by adelarsq** [comment]
@chemzqm We can take ideas from [vim-vebugger](https://github.com/idanarye/vim-vebugger/blob/develop/doc/vebugger.txt). About buttons, we can use [denite](https://github.com/Shougo/denite.nvim) or [quickmenu](https://github.com/skywind3000/quickmenu.vim) to provide buttons.

**Comment by aeosynth** [comment]
there are a bunch of vim debuggers to look at for ideas, here's one which even uses the debug protocol (i haven't used it): https://github.com/puremourning/vimspector

**Comment by chemzqm** [comment]
I've experienced with emmet completion in VSCode, I think it's worthy to have it, since it would help to reduce the number of key stroke you need to use for snippet.

**Comment by adelarsq** [comment]
@chemzqm Would be nice. Actually I use [emmet-vim](https://github.com/mattn/emmet-vim) with `<c-e>` as leader key.

**Comment by Moroxus** [comment]
Is it possible to add semantic highlighting through LSP protocol?

**Comment by chemzqm** [comment]
@Moroxus LSP don't have semantic highlight yet, but it's possible for coc to implement.

**Comment by oblitum** [comment]
@ovidius72 it's possible, through Unicode and font with colored characters/emoji (plus terminal support of that if you're on terminal). There's no option for enabling or tweaking that in coc though.

**Comment by ovidius72** [comment]
Thanks @oblitum 
I'm on terminal. I have nerd fonts working fine but unfortunately have no idea where to start.
I joined the vim word only a few weeks ago.
Can you suggest any tutorial or doc where I can start from ?

**Comment by oblitum** [comment]
@ovidius72 hi, I just meant that it's not impossible, since you can use emoji/unicode/custom-fonts for that, but coc.nvim doesn't provide options for tweaking `kind` or other parts of the menu, which may vary depending on language, that's up to @chemzqm or your willing to fork/patch it to put Unicode in it.

**Comment by oblitum** [comment]
@ovidius72 you would put your emoji around here: https://github.com/neoclide/coc.nvim/blob/master/src/util/complete.ts#L72

**Comment by oblitum** [comment]
@ovidius72, for example:

- cd `~/.vim/plugged/coc.nvim`

- ```diff
  @@ -74,7 +74,7 @@ export function completionKindString(kind: CompletionItemKind): string {
       case CompletionItemKind.Text:
         return 'Text'
       case CompletionItemKind.Method:
  -      return 'Method'
  +      return '📙'
       case CompletionItemKind.Function:
         return 'Function'
       case CompletionItemKind.Constructor:
  ```

- `yarn install`

- `nvim sample.cpp`
  ![imgur-21 03 08_28-12-2018](https://user-images.githubusercontent.com/1269815/50530429-70097500-0ae4-11e9-9de8-5d739c116cf5.png)

**Comment by ovidius72** [comment]
@oblitum Wow this is nice. 
I'll take a look at it as soon as possible. Is it also possible to show them at the left side ?
Thanks.

**Comment by oblitum** [comment]
@ovidius72 anything is possible, since it's open source, good luck maintaining the patch though.

**Comment by oblitum** [comment]
@ovidius72 the kind of the completion is generally shown in the middle though, never left-side, it's the way Vim does things, you could try patching it for that but you would be really going against how Vim works, to the point you better stick to vscode.

**Comment by theFool32** [comment]
I find the repo [coc-jedi](https://github.com/neoclide/coc-jedi), does it conflict with the integration of Microsoft/vscode-python?

BTW, what's the difference between the sources (vim plugins?) and extensions (node package?). I'm new to coc.nvim and vimL, and wonder whether there exist a fast and easy way to port something like [ncm2-tmux](https://github.com/ncm2/ncm2-tmux),  [ncm2-look](https://github.com/filipekiss/ncm2-look.vim) and [ncm2-en](https://github.com/theFool32/ncm2-en) to coc.nvim.

Thanks.

**Comment by chemzqm** [comment]
> does it conflict with the integration of Microsoft/vscode-python?

It does

> what's the difference between the sources (vim plugins?) and extensions (node package?)

Coc load sources from viml plugin as extension internally, the source could be implemented in viml as vim plugin, or javascript as node package. The call to viml function could quite slow, and block your typing, so it's recommended to use node module, and it could make use of javascript APIs from coc.

>  whether there exist a fast and easy way to port something like ncm2-tmux

Not yet, but possible in the feature.

**Comment by oblitum** [comment]
@kutsan you can use configuration from `.vimrc` and ditch `coc-settings.json`, check `:h coc#config()`, [example](https://github.com/oblitum/dotfiles/blob/98b81b6104d5d590184746d335364d2d5576456f/.vimrc#L1234-L1283).

**Comment by kutsan** [comment]
@oblitum Oh, thanks; that was what I wanted in the first place.

**Comment by oblitum** [comment]
@kutsan fyi, updated [example](https://github.com/oblitum/dotfiles/blob/f3f2ca1c8f6d3ff506541f6de02bd20d999eae81/.vimrc#L1234-L1285), due to [breaking changes](https://github.com/oblitum/dotfiles/commit/f3f2ca1c8f6d3ff506541f6de02bd20d999eae81).

**Comment by sandangel** [comment]
@chemzqm I think you also need to change the coc.txt file as well 
```
g:rooter_patterns 				*g:rooter_patterns*

			To specify how to identify a project's root directory >

			let g:rooter_patterns = ['Rakefile', '.git/']
<

			default to `['.vim/', '.git/', '.hg/', '.projections.json']`

			Note: you can specify different project root for
			language servers by use `rootPatterns` in
			settings.json.
```

**Comment by rbpatt2019** [comment]
Thanks for the great work @chemzqm! I've found pyls to be a bit of a pain and look forward to coc.nvim with the Micorsoft Python extension!

**Comment by kabouzeid** [comment]
> I find the repo [coc-jedi](https://github.com/neoclide/coc-jedi), does it conflict with the integration of Microsoft/vscode-python?
> 
> BTW, what's the difference between the sources (vim plugins?) and extensions (node package?). I'm new to coc.nvim and vimL, and wonder whether there exist a fast and easy way to port something like [ncm2-tmux](https://github.com/ncm2/ncm2-tmux), [ncm2-look](https://github.com/filipekiss/ncm2-look.vim) and [ncm2-en](https://github.com/theFool32/ncm2-en) to coc.nvim.
> 
> Thanks.

@theFool32 I've added support for tmux-complete (https://github.com/wellle/tmux-complete.vim/pull/84/files)

**Comment by oblitum** [comment]
Hello.

The current state is rather confusing for coc.nvim, as there isn't release tags anymore since 08/2019 and compiled state is being pushed to the release branch since then. Given that, does this issue represent anything yet? Should it be closed or is there's still plans for reaching 0.1?

**Comment by chemzqm** [comment]
Need lots of tests, but I don't have time to recently.

**Comment by carlosala** [comment]
Is there going to be a new release? I saw that this issue seems a little bit abandoned. Should we use directly master or just wait for release be updated (talking about production, of course)

**Comment by oblitum** [comment]
@carlosala the release branch, as instructed from readme, doesn't require compilation from user. Each commit in that branch is a release.

**Comment by chemzqm** [comment]
> Can we close this issue to avoid confusion?

No.

**Comment by chemzqm** [comment]
This roadmap is from the v0.1 era (2018) and almost everything on it has landed or been superseded:

- Vim support, airline/lightline, neosnippet, binary distribution, settings command, document highlight/link, codeLens, emmet extension, python integration — all shipped.
- Test coverage: coc.nvim now has a substantial Vitest suite (119 test files, ~3400 tests, including integration tests that boot Vim/Neovim and a real language server).
- coc-tester: https://github.com/neoclide/coc-test
- LSP 3.18: the client tracks the latest vscode-languageserver-protocol; newer protocol features are tracked per-feature in their own issues/PRs.
- coc-vscode: use https://github.com/coc-plugin/coc-vscode-loader

The remaining items are better tracked individually (protocol features as they appear upstream, testing coverage as a continuous goal) rather than in a single 2018 milestone issue, so I'm closing this roadmap. Individual feature requests are still welcome as separate issues.
